version: '3.9'
name: fractal
services:
  api:
    container_name: fractal_api
    build:
      dockerfile: Dockerfile
      context: ../packages/api
    ports:
      - '3000:${API_PORT:-3000}'
    depends_on:
      - postgres
  admin:
    container_name: fractal_admin
    build:
      dockerfile: Dockerfile
      context: ../packages/admin
    ports:
      - '80:${ADMIN_PORT:-3001}'
    depends_on:
      - postgres
  postgres:
    container_name: fractal_postgresql
    image: postgres:14.8-alpine3.18
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-fractal}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qweQWE123!}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./data/postgres/init:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DATABASE:-startapp}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
